// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ainsleyclark/godaily/pkg/services/social/platform (interfaces: Poster)
//
// Generated by this command:
//
//	mockgen -package=mocksocial -destination=../../../mocks/social/Poster.go github.com/ainsleyclark/godaily/pkg/services/social/platform Poster
//

// Package mocksocial is a generated GoMock package.
package mocksocial

import (
	context "context"
	reflect "reflect"

	social "github.com/ainsleyclark/godaily/pkg/domain/social"
	platform "github.com/ainsleyclark/godaily/pkg/services/social/platform"
	gomock "go.uber.org/mock/gomock"
)

// MockPoster is a mock of Poster interface.
type MockPoster struct {
	ctrl     *gomock.Controller
	recorder *MockPosterMockRecorder
	isgomock struct{}
}

// MockPosterMockRecorder is the mock recorder for MockPoster.
type MockPosterMockRecorder struct {
	mock *MockPoster
}

// NewMockPoster creates a new mock instance.
func NewMockPoster(ctrl *gomock.Controller) *MockPoster {
	mock := &MockPoster{ctrl: ctrl}
	mock.recorder = &MockPosterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPoster) EXPECT() *MockPosterMockRecorder {
	return m.recorder
}

// Platform mocks base method.
func (m *MockPoster) Platform() social.Platform {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Platform")
	ret0, _ := ret[0].(social.Platform)
	return ret0
}

// Platform indicates an expected call of Platform.
func (mr *MockPosterMockRecorder) Platform() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Platform", reflect.TypeOf((*MockPoster)(nil).Platform))
}

// Post mocks base method.
func (m *MockPoster) Post(ctx context.Context, text string) (platform.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post", ctx, text)
	ret0, _ := ret[0].(platform.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Post indicates an expected call of Post.
func (mr *MockPosterMockRecorder) Post(ctx, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockPoster)(nil).Post), ctx, text)
}
