// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ainsleyclark/godaily/pkg/domain/social (interfaces: PostRepository)
//
// Generated by this command:
//
//	mockgen -package=mocksocial -destination=../../mocks/social/PostRepository.go . PostRepository
//

// Package mocksocial is a generated GoMock package.
package mocksocial

import (
	context "context"
	reflect "reflect"
	time "time"

	social "github.com/ainsleyclark/godaily/pkg/domain/social"
	gomock "go.uber.org/mock/gomock"
)

// MockPostRepository is a mock of PostRepository interface.
type MockPostRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPostRepositoryMockRecorder
	isgomock struct{}
}

// MockPostRepositoryMockRecorder is the mock recorder for MockPostRepository.
type MockPostRepositoryMockRecorder struct {
	mock *MockPostRepository
}

// NewMockPostRepository creates a new mock instance.
func NewMockPostRepository(ctrl *gomock.Controller) *MockPostRepository {
	mock := &MockPostRepository{ctrl: ctrl}
	mock.recorder = &MockPostRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostRepository) EXPECT() *MockPostRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPostRepository) Create(ctx context.Context, p social.Post) (social.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(social.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPostRepositoryMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPostRepository)(nil).Create), ctx, p)
}

// HasPosted mocks base method.
func (m *MockPostRepository) HasPosted(ctx context.Context, issueID int64, platform string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPosted", ctx, issueID, platform)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasPosted indicates an expected call of HasPosted.
func (mr *MockPostRepositoryMockRecorder) HasPosted(ctx, issueID, platform any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPosted", reflect.TypeOf((*MockPostRepository)(nil).HasPosted), ctx, issueID, platform)
}

// HasPostedBySubject mocks base method.
func (m *MockPostRepository) HasPostedBySubject(ctx context.Context, subject, platform string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPostedBySubject", ctx, subject, platform)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasPostedBySubject indicates an expected call of HasPostedBySubject.
func (mr *MockPostRepositoryMockRecorder) HasPostedBySubject(ctx, subject, platform any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPostedBySubject", reflect.TypeOf((*MockPostRepository)(nil).HasPostedBySubject), ctx, subject, platform)
}

// HasPostedKindSince mocks base method.
func (m *MockPostRepository) HasPostedKindSince(ctx context.Context, kind social.PostKind, platform string, since time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPostedKindSince", ctx, kind, platform, since)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasPostedKindSince indicates an expected call of HasPostedKindSince.
func (mr *MockPostRepositoryMockRecorder) HasPostedKindSince(ctx, kind, platform, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPostedKindSince", reflect.TypeOf((*MockPostRepository)(nil).HasPostedKindSince), ctx, kind, platform, since)
}

// List mocks base method.
func (m *MockPostRepository) List(ctx context.Context, opts social.PostListOptions) ([]social.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].([]social.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPostRepositoryMockRecorder) List(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPostRepository)(nil).List), ctx, opts)
}
