// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ainsleyclark/godaily/pkg/domain/social (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -package=mocksocial -destination=../../mocks/social/Service.go . Service
//

// Package mocksocial is a generated GoMock package.
package mocksocial

import (
	context "context"
	reflect "reflect"

	social "github.com/ainsleyclark/godaily/pkg/domain/social"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// DraftFeatured mocks base method.
func (m *MockService) DraftFeatured(ctx context.Context, opts social.PostOptions) ([]social.PostResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DraftFeatured", ctx, opts)
	ret0, _ := ret[0].([]social.PostResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DraftFeatured indicates an expected call of DraftFeatured.
func (mr *MockServiceMockRecorder) DraftFeatured(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DraftFeatured", reflect.TypeOf((*MockService)(nil).DraftFeatured), ctx, opts)
}

// PublishDrafts mocks base method.
func (m *MockService) PublishDrafts(ctx context.Context, opts social.PostOptions) ([]social.PostResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishDrafts", ctx, opts)
	ret0, _ := ret[0].([]social.PostResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishDrafts indicates an expected call of PublishDrafts.
func (mr *MockServiceMockRecorder) PublishDrafts(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishDrafts", reflect.TypeOf((*MockService)(nil).PublishDrafts), ctx, opts)
}

// Rotate mocks base method.
func (m *MockService) Rotate(ctx context.Context, opts social.RotateOptions) ([]social.PostResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rotate", ctx, opts)
	ret0, _ := ret[0].([]social.PostResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Rotate indicates an expected call of Rotate.
func (mr *MockServiceMockRecorder) Rotate(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rotate", reflect.TypeOf((*MockService)(nil).Rotate), ctx, opts)
}
