// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ainsleyclark/godaily/pkg/domain/social (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -package=mocksocial -destination=../../mocks/social/Service.go . Service
//

// Package mocksocial is a generated GoMock package.
package mocksocial

import (
	context "context"
	reflect "reflect"

	social "github.com/ainsleyclark/godaily/pkg/domain/social"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// HasPosters mocks base method.
func (m *MockService) HasPosters() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPosters")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasPosters indicates an expected call of HasPosters.
func (mr *MockServiceMockRecorder) HasPosters() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPosters", reflect.TypeOf((*MockService)(nil).HasPosters))
}

// Post mocks base method.
func (m *MockService) Post(ctx context.Context, opts social.PostOptions) ([]social.PostResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post", ctx, opts)
	ret0, _ := ret[0].([]social.PostResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Post indicates an expected call of Post.
func (mr *MockServiceMockRecorder) Post(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockService)(nil).Post), ctx, opts)
}

// Rotate mocks base method.
func (m *MockService) Rotate(ctx context.Context, opts social.RotateOptions) ([]social.PostResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rotate", ctx, opts)
	ret0, _ := ret[0].([]social.PostResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Rotate indicates an expected call of Rotate.
func (mr *MockServiceMockRecorder) Rotate(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rotate", reflect.TypeOf((*MockService)(nil).Rotate), ctx, opts)
}
