// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ainsleyclark/godaily/pkg/gateway/social (interfaces: StatFetcher)
//
// Generated by this command:
//
//	mockgen -package=mocksocial -destination=../../mocks/social/StatFetcher.go github.com/ainsleyclark/godaily/pkg/gateway/social StatFetcher
//

// Package mocksocial is a generated GoMock package.
package mocksocial

import (
	context "context"
	reflect "reflect"

	social "github.com/ainsleyclark/godaily/pkg/gateway/social"
	gomock "go.uber.org/mock/gomock"
)

// MockStatFetcher is a mock of StatFetcher interface.
type MockStatFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockStatFetcherMockRecorder
	isgomock struct{}
}

// MockStatFetcherMockRecorder is the mock recorder for MockStatFetcher.
type MockStatFetcherMockRecorder struct {
	mock *MockStatFetcher
}

// NewMockStatFetcher creates a new mock instance.
func NewMockStatFetcher(ctrl *gomock.Controller) *MockStatFetcher {
	mock := &MockStatFetcher{ctrl: ctrl}
	mock.recorder = &MockStatFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatFetcher) EXPECT() *MockStatFetcherMockRecorder {
	return m.recorder
}

// Platform mocks base method.
func (m *MockStatFetcher) Platform() social.Platform {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Platform")
	ret0, _ := ret[0].(social.Platform)
	return ret0
}

// Platform indicates an expected call of Platform.
func (mr *MockStatFetcherMockRecorder) Platform() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Platform", reflect.TypeOf((*MockStatFetcher)(nil).Platform))
}

// Stats mocks base method.
func (m *MockStatFetcher) Stats(ctx context.Context, postURL string) (social.Stats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stats", ctx, postURL)
	ret0, _ := ret[0].(social.Stats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stats indicates an expected call of Stats.
func (mr *MockStatFetcherMockRecorder) Stats(ctx, postURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stats", reflect.TypeOf((*MockStatFetcher)(nil).Stats), ctx, postURL)
}
