// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ainsleyclark/godaily/pkg/domain/digest (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -package=mockdigest -destination=../../mocks/digest/Service.go . Service
//

// Package mockdigest is a generated GoMock package.
package mockdigest

import (
	context "context"
	reflect "reflect"
	time "time"

	digest "github.com/ainsleyclark/godaily/pkg/domain/digest"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MockService) Build(ctx context.Context, date time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build", ctx, date)
	ret0, _ := ret[0].(error)
	return ret0
}

// Build indicates an expected call of Build.
func (mr *MockServiceMockRecorder) Build(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockService)(nil).Build), ctx, date)
}

// Collect mocks base method.
func (m *MockService) Collect(ctx context.Context, opts digest.CollectOptions) (digest.CollectResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collect", ctx, opts)
	ret0, _ := ret[0].(digest.CollectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Collect indicates an expected call of Collect.
func (mr *MockServiceMockRecorder) Collect(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collect", reflect.TypeOf((*MockService)(nil).Collect), ctx, opts)
}

// SendDigest mocks base method.
func (m *MockService) SendDigest(ctx context.Context, date time.Time, force bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendDigest", ctx, date, force)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendDigest indicates an expected call of SendDigest.
func (mr *MockServiceMockRecorder) SendDigest(ctx, date, force any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendDigest", reflect.TypeOf((*MockService)(nil).SendDigest), ctx, date, force)
}

// SendPreview mocks base method.
func (m *MockService) SendPreview(ctx context.Context, date time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPreview", ctx, date)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPreview indicates an expected call of SendPreview.
func (mr *MockServiceMockRecorder) SendPreview(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPreview", reflect.TypeOf((*MockService)(nil).SendPreview), ctx, date)
}

// SendSuggestion mocks base method.
func (m *MockService) SendSuggestion(ctx context.Context, date time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendSuggestion", ctx, date)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendSuggestion indicates an expected call of SendSuggestion.
func (mr *MockServiceMockRecorder) SendSuggestion(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendSuggestion", reflect.TypeOf((*MockService)(nil).SendSuggestion), ctx, date)
}
