// Copyright (c) 2026 godaily (Ainsley Clark) All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package social

import (
	"context"
	"time"
)

// Post records a single social media post in one of three lifecycle
// states: a draft generated by Build (text only, never sent), a published
// row that hit the platform, or an error row whose publish attempt failed
// and is awaiting retry. Featured posts link back to a digest issue via
// IssueID; rotation posts (recap, spotlight, cta, self_release) leave
// IssueID nil and use Subject as their idempotency key
// (e.g. "spotlight:ardanlabs", "self_release:v1.4.0", "recap:2026-W21").
//
// MentionSource is the news.Source slug whose ProfileFor mentions should
// be attached at publish time. It is persisted on the draft so the publish
// step does not need to re-run the AI feature pick.
type Post struct {
	ID            int64      `json:"id"`
	IssueID       *int64     `json:"issue_id,omitempty"`
	Kind          PostKind   `json:"kind"`
	Subject       string     `json:"subject,omitempty"`
	Platform      string     `json:"platform"`
	Text          string     `json:"text"`
	PostURL       string     `json:"post_url,omitempty"`
	PostedAt      time.Time  `json:"posted_at"`
	Status        PostStatus `json:"status"`
	PublishedAt   *time.Time `json:"published_at,omitempty"`
	MentionSource string     `json:"mention_source,omitempty"`
}

// PostStatus tracks where a row sits in the draft → publish → error
// lifecycle. Build inserts rows as Draft; the publish cron transitions
// them to Published (or Error on failure).
type PostStatus string

const (
	// PostStatusDraft is the row's initial state after Build has run the
	// AI reframer but before the platform has actually been called. The
	// admin edit window operates exclusively on these rows.
	PostStatusDraft PostStatus = "draft"

	// PostStatusPublished marks a row whose text was successfully sent
	// to its platform; PostURL and PublishedAt are populated.
	PostStatusPublished PostStatus = "published"

	// PostStatusError marks a row whose platform send failed. The row
	// stays visible (text intact) so a future retry can revert it to
	// Draft and republish.
	PostStatusError PostStatus = "error"
)

// PostKind classifies what flavour of social post a row represents.
// 'featured' rows pair with an issue and come from the daily 11 UTC slot;
// the rotation kinds run from the Tue/Fri rotation slot and use Subject
// for idempotency instead of IssueID.
type PostKind string

const (
	// PostKindFeatured is the daily AI-picked post anchored to an issue.
	PostKindFeatured PostKind = "featured"

	// PostKindNewSource announces that GoDaily started pulling from a
	// new source. Subject is "new_source:<source>".
	PostKindNewSource PostKind = "new_source"

	// PostKindRecap is the Friday weekly top-clicks post.
	PostKindRecap PostKind = "recap"

	// PostKindSpotlight tags and boosts a curated source.
	PostKindSpotlight PostKind = "spotlight"

	// PostKindCTA is a "sign up to GoDaily" rotation post.
	PostKindCTA PostKind = "cta"

	// PostKindCommunity is the Wednesday community-promo post that tags
	// a Go conference or meetup. Subject is "community:<slug>:<year>".
	PostKindCommunity PostKind = "community"
)

// PostListOptions filters a List query. At least one field must be set.
// All filters AND together; nil fields are ignored.
type PostListOptions struct {
	// IssueID restricts results to posts for a specific issue, oldest first.
	IssueID *int64
	// Since restricts results to posts with posted_at >= Since, newest first.
	Since *time.Time
	// Status restricts to a single lifecycle state (draft, published, error).
	Status *PostStatus
	// Platform restricts to a single platform (bluesky, linkedin, mastodon).
	Platform *string
}

//go:generate go run go.uber.org/mock/mockgen -package=mocksocial -destination=../../mocks/social/PostRepository.go . PostRepository

// PostRepository defines the methods for interacting with the social_posts store.
type PostRepository interface {
	// HasPosted reports whether a featured row exists for the given issue
	// and platform. Used by the daily featured slot.
	HasPosted(ctx context.Context, issueID int64, platform string) (bool, error)

	// HasPostedBySubject reports whether any row exists with the given
	// subject and platform. Used by rotation candidates that key off a
	// stable subject (release tag, source slug, recap week, cta variant).
	HasPostedBySubject(ctx context.Context, subject, platform string) (bool, error)

	// HasPostedKindSince reports whether any row of the given kind on the
	// given platform was posted at or after since. Used to throttle the
	// CTA and recap rotations.
	HasPostedKindSince(ctx context.Context, kind PostKind, platform string, since time.Time) (bool, error)

	// Create persists a new social post record.
	Create(ctx context.Context, p Post) (Post, error)

	// UpdateStatus transitions a row to a new lifecycle state. It is the
	// single mutation point used by the publish step to mark a draft as
	// published (with PublishedAt + PostURL) or as errored.
	UpdateStatus(ctx context.Context, id int64, status PostStatus, publishedAt *time.Time, postURL string) (Post, error)

	// DeleteDraftsByIssue removes any draft rows associated with the
	// issue. Build calls this before regenerating drafts so a re-run for
	// the same day cleanly replaces the previous attempt.
	DeleteDraftsByIssue(ctx context.Context, issueID int64) error

	// List returns social posts filtered by opts. At least one option must be set.
	List(ctx context.Context, opts PostListOptions) ([]Post, error)
}
