// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ainsleyclark/godaily/pkg/domain/news (interfaces: SocialPostRepository)
//
// Generated by this command:
//
//	mockgen -package=mocknews -destination=../../mocks/domain/news/SocialPostRepository.go . SocialPostRepository
//

// Package mocknews is a generated GoMock package.
package mocknews

import (
	context "context"
	reflect "reflect"
	time "time"

	news "github.com/ainsleyclark/godaily/pkg/domain/news"
	gomock "go.uber.org/mock/gomock"
)

// MockSocialPostRepository is a mock of SocialPostRepository interface.
type MockSocialPostRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSocialPostRepositoryMockRecorder
	isgomock struct{}
}

// MockSocialPostRepositoryMockRecorder is the mock recorder for MockSocialPostRepository.
type MockSocialPostRepositoryMockRecorder struct {
	mock *MockSocialPostRepository
}

// NewMockSocialPostRepository creates a new mock instance.
func NewMockSocialPostRepository(ctrl *gomock.Controller) *MockSocialPostRepository {
	mock := &MockSocialPostRepository{ctrl: ctrl}
	mock.recorder = &MockSocialPostRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSocialPostRepository) EXPECT() *MockSocialPostRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSocialPostRepository) Create(ctx context.Context, p news.SocialPost) (news.SocialPost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(news.SocialPost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSocialPostRepositoryMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSocialPostRepository)(nil).Create), ctx, p)
}

// HasPosted mocks base method.
func (m *MockSocialPostRepository) HasPosted(ctx context.Context, issueID int64, platform string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPosted", ctx, issueID, platform)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasPosted indicates an expected call of HasPosted.
func (mr *MockSocialPostRepositoryMockRecorder) HasPosted(ctx, issueID, platform any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPosted", reflect.TypeOf((*MockSocialPostRepository)(nil).HasPosted), ctx, issueID, platform)
}

// HasPostedBySubject mocks base method.
func (m *MockSocialPostRepository) HasPostedBySubject(ctx context.Context, subject, platform string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPostedBySubject", ctx, subject, platform)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasPostedBySubject indicates an expected call of HasPostedBySubject.
func (mr *MockSocialPostRepositoryMockRecorder) HasPostedBySubject(ctx, subject, platform any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPostedBySubject", reflect.TypeOf((*MockSocialPostRepository)(nil).HasPostedBySubject), ctx, subject, platform)
}

// HasPostedKindSince mocks base method.
func (m *MockSocialPostRepository) HasPostedKindSince(ctx context.Context, kind news.SocialPostKind, platform string, since time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPostedKindSince", ctx, kind, platform, since)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasPostedKindSince indicates an expected call of HasPostedKindSince.
func (mr *MockSocialPostRepositoryMockRecorder) HasPostedKindSince(ctx, kind, platform, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPostedKindSince", reflect.TypeOf((*MockSocialPostRepository)(nil).HasPostedKindSince), ctx, kind, platform, since)
}

// List mocks base method.
func (m *MockSocialPostRepository) List(ctx context.Context, opts news.SocialPostListOptions) ([]news.SocialPost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].([]news.SocialPost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSocialPostRepositoryMockRecorder) List(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSocialPostRepository)(nil).List), ctx, opts)
}
