// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ainsleyclark/godaily/pkg/gateway/email (interfaces: BatchSender)
//
// Generated by this command:
//
//	mockgen -package=mockemail -destination=../../mocks/email/BatchSender.go . BatchSender
//

// Package mockemail is a generated GoMock package.
package mockemail

import (
	context "context"
	reflect "reflect"

	email "github.com/ainsleyclark/godaily/pkg/gateway/email"
	gomock "go.uber.org/mock/gomock"
)

// MockBatchSender is a mock of BatchSender interface.
type MockBatchSender struct {
	ctrl     *gomock.Controller
	recorder *MockBatchSenderMockRecorder
	isgomock struct{}
}

// MockBatchSenderMockRecorder is the mock recorder for MockBatchSender.
type MockBatchSenderMockRecorder struct {
	mock *MockBatchSender
}

// NewMockBatchSender creates a new mock instance.
func NewMockBatchSender(ctrl *gomock.Controller) *MockBatchSender {
	mock := &MockBatchSender{ctrl: ctrl}
	mock.recorder = &MockBatchSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatchSender) EXPECT() *MockBatchSenderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockBatchSender) Send(ctx context.Context, req email.SendEmailRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockBatchSenderMockRecorder) Send(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockBatchSender)(nil).Send), ctx, req)
}

// SendBatch mocks base method.
func (m *MockBatchSender) SendBatch(ctx context.Context, reqs []*email.SendEmailRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendBatch", ctx, reqs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendBatch indicates an expected call of SendBatch.
func (mr *MockBatchSenderMockRecorder) SendBatch(ctx, reqs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBatch", reflect.TypeOf((*MockBatchSender)(nil).SendBatch), ctx, reqs)
}
