// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ainsleyclark/godaily/pkg/domain/audience (interfaces: SubscriberService)
//
// Generated by this command:
//
//	mockgen -package=mockaudience -destination=../../mocks/audience/Service.go . SubscriberService
//

// Package mockaudience is a generated GoMock package.
package mockaudience

import (
	context "context"
	reflect "reflect"

	audience "github.com/ainsleyclark/godaily/pkg/domain/audience"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of SubscriberService interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Confirm mocks base method.
func (m *MockService) Confirm(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Confirm", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Confirm indicates an expected call of Confirm.
func (mr *MockServiceMockRecorder) Confirm(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Confirm", reflect.TypeOf((*MockService)(nil).Confirm), ctx, token)
}

// MarkBounced mocks base method.
func (m *MockService) MarkBounced(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkBounced", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkBounced indicates an expected call of MarkBounced.
func (mr *MockServiceMockRecorder) MarkBounced(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkBounced", reflect.TypeOf((*MockService)(nil).MarkBounced), ctx, email)
}

// MarkComplained mocks base method.
func (m *MockService) MarkComplained(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkComplained", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkComplained indicates an expected call of MarkComplained.
func (mr *MockServiceMockRecorder) MarkComplained(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkComplained", reflect.TypeOf((*MockService)(nil).MarkComplained), ctx, email)
}

// MarkSuppressed mocks base method.
func (m *MockService) MarkSuppressed(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSuppressed", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSuppressed indicates an expected call of MarkSuppressed.
func (mr *MockServiceMockRecorder) MarkSuppressed(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSuppressed", reflect.TypeOf((*MockService)(nil).MarkSuppressed), ctx, email)
}

// Subscribe mocks base method.
func (m *MockService) Subscribe(ctx context.Context, email string) (audience.Subscriber, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, email)
	ret0, _ := ret[0].(audience.Subscriber)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockServiceMockRecorder) Subscribe(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockService)(nil).Subscribe), ctx, email)
}

// Unsubscribe mocks base method.
func (m *MockService) Unsubscribe(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unsubscribe", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockServiceMockRecorder) Unsubscribe(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockService)(nil).Unsubscribe), ctx, token)
}
