// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"
)

type Issue struct {
	ID      int64          `json:"id"`
	Slug    string         `json:"slug"`
	SentAt  time.Time      `json:"sent_at"`
	Subject string         `json:"subject"`
	Summary sql.NullString `json:"summary"`
	Status  string         `json:"status"`
}

type Item struct {
	ID               int64           `json:"id"`
	IssueID          int64           `json:"issue_id"`
	Source           string          `json:"source"`
	Title            string          `json:"title"`
	Url              string          `json:"url"`
	Tag              string          `json:"tag"`
	AuthorName       sql.NullString  `json:"author_name"`
	AuthorUsername   sql.NullString  `json:"author_username"`
	AuthorAvatarUrl  sql.NullString  `json:"author_avatar_url"`
	AuthorProfileUrl sql.NullString  `json:"author_profile_url"`
	Score            sql.NullFloat64 `json:"score"`
	Summary          sql.NullString  `json:"summary"`
	Position         int64           `json:"position"`
	OriginalUrl      sql.NullString  `json:"original_url"`
}

type Subscriber struct {
	ID               int64          `json:"id"`
	Email            string         `json:"email"`
	UnsubscribeToken string         `json:"unsubscribe_token"`
	UnsubscribedAt   *time.Time     `json:"unsubscribed_at"`
	CreatedAt        time.Time      `json:"created_at"`
	ConfirmToken     sql.NullString `json:"confirm_token"`
	ConfirmedAt      *time.Time     `json:"confirmed_at"`
}
