// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const issueByID = `-- name: IssueByID :one
SELECT id, slug, sent_at, subject, summary, status FROM issues WHERE id = ? LIMIT 1
`

func (q *Queries) IssueByID(ctx context.Context, id int64) (Issue, error) {
	row := q.db.QueryRowContext(ctx, issueByID, id)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.SentAt,
		&i.Subject,
		&i.Summary,
		&i.Status,
	)
	return i, err
}

const issueBySlug = `-- name: IssueBySlug :one
SELECT id, slug, sent_at, subject, summary, status FROM issues WHERE slug = ? LIMIT 1
`

func (q *Queries) IssueBySlug(ctx context.Context, slug string) (Issue, error) {
	row := q.db.QueryRowContext(ctx, issueBySlug, slug)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.SentAt,
		&i.Subject,
		&i.Summary,
		&i.Status,
	)
	return i, err
}

const issueCount = `-- name: IssueCount :one
SELECT COUNT(*) FROM issues WHERE status = 'sent'
`

func (q *Queries) IssueCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, issueCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const issueCreate = `-- name: IssueCreate :one
INSERT INTO issues (
    slug, sent_at, subject, summary, status
) VALUES (
    ?, ?, ?, ?, ?
)
RETURNING id, slug, sent_at, subject, summary, status
`

type IssueCreateParams struct {
	Slug    string         `json:"slug"`
	SentAt  time.Time      `json:"sent_at"`
	Subject string         `json:"subject"`
	Summary sql.NullString `json:"summary"`
	Status  string         `json:"status"`
}

func (q *Queries) IssueCreate(ctx context.Context, arg IssueCreateParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, issueCreate,
		arg.Slug,
		arg.SentAt,
		arg.Subject,
		arg.Summary,
		arg.Status,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.SentAt,
		&i.Subject,
		&i.Summary,
		&i.Status,
	)
	return i, err
}

const issueList = `-- name: IssueList :many
SELECT id, slug, sent_at, subject, summary, status FROM issues
WHERE status = 'sent'
ORDER BY sent_at DESC
LIMIT ? OFFSET ?
`

type IssueListParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) IssueList(ctx context.Context, arg IssueListParams) ([]Issue, error) {
	rows, err := q.db.QueryContext(ctx, issueList, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.SentAt,
			&i.Subject,
			&i.Summary,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const issueUpdateStatus = `-- name: IssueUpdateStatus :one
UPDATE issues SET status = ?, sent_at = ? WHERE id = ? RETURNING id, slug, sent_at, subject, summary, status
`

type IssueUpdateStatusParams struct {
	Status string    `json:"status"`
	SentAt time.Time `json:"sent_at"`
	ID     int64     `json:"id"`
}

func (q *Queries) IssueUpdateStatus(ctx context.Context, arg IssueUpdateStatusParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, issueUpdateStatus, arg.Status, arg.SentAt, arg.ID)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.SentAt,
		&i.Subject,
		&i.Summary,
		&i.Status,
	)
	return i, err
}

const itemByID = `-- name: ItemByID :one
SELECT id, issue_id, source, title, url, author_name, author_username, author_avatar_url, author_profile_url, score, summary, position FROM items WHERE id = ? LIMIT 1
`

func (q *Queries) ItemByID(ctx context.Context, id int64) (Item, error) {
	row := q.db.QueryRowContext(ctx, itemByID, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Source,
		&i.Title,
		&i.Url,
		&i.AuthorName,
		&i.AuthorUsername,
		&i.AuthorAvatarUrl,
		&i.AuthorProfileUrl,
		&i.Score,
		&i.Summary,
		&i.Position,
	)
	return i, err
}

const itemCreate = `-- name: ItemCreate :one
INSERT INTO items (
    issue_id, source, title, url,
    author_name, author_username, author_avatar_url, author_profile_url,
    score, summary, position
) VALUES (
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?
)
RETURNING id, issue_id, source, title, url, author_name, author_username, author_avatar_url, author_profile_url, score, summary, position
`

type ItemCreateParams struct {
	IssueID          int64           `json:"issue_id"`
	Source           string          `json:"source"`
	Title            string          `json:"title"`
	Url              string          `json:"url"`
	AuthorName       sql.NullString  `json:"author_name"`
	AuthorUsername   sql.NullString  `json:"author_username"`
	AuthorAvatarUrl  sql.NullString  `json:"author_avatar_url"`
	AuthorProfileUrl sql.NullString  `json:"author_profile_url"`
	Score            sql.NullFloat64 `json:"score"`
	Summary          sql.NullString  `json:"summary"`
	Position         int64           `json:"position"`
}

func (q *Queries) ItemCreate(ctx context.Context, arg ItemCreateParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, itemCreate,
		arg.IssueID,
		arg.Source,
		arg.Title,
		arg.Url,
		arg.AuthorName,
		arg.AuthorUsername,
		arg.AuthorAvatarUrl,
		arg.AuthorProfileUrl,
		arg.Score,
		arg.Summary,
		arg.Position,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Source,
		&i.Title,
		&i.Url,
		&i.AuthorName,
		&i.AuthorUsername,
		&i.AuthorAvatarUrl,
		&i.AuthorProfileUrl,
		&i.Score,
		&i.Summary,
		&i.Position,
	)
	return i, err
}

const itemDeleteByIssue = `-- name: ItemDeleteByIssue :exec
DELETE FROM items WHERE issue_id = ?
`

func (q *Queries) ItemDeleteByIssue(ctx context.Context, issueID int64) error {
	_, err := q.db.ExecContext(ctx, itemDeleteByIssue, issueID)
	return err
}

const itemListByIssue = `-- name: ItemListByIssue :many
SELECT id, issue_id, source, title, url, author_name, author_username, author_avatar_url, author_profile_url, score, summary, position FROM items
WHERE issue_id = ?
ORDER BY position ASC
`

func (q *Queries) ItemListByIssue(ctx context.Context, issueID int64) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, itemListByIssue, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.Source,
			&i.Title,
			&i.Url,
			&i.AuthorName,
			&i.AuthorUsername,
			&i.AuthorAvatarUrl,
			&i.AuthorProfileUrl,
			&i.Score,
			&i.Summary,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subscriberByEmail = `-- name: SubscriberByEmail :one
SELECT id, email, unsubscribe_token, unsubscribed_at, created_at FROM subscribers WHERE email = ? LIMIT 1
`

func (q *Queries) SubscriberByEmail(ctx context.Context, email string) (Subscriber, error) {
	row := q.db.QueryRowContext(ctx, subscriberByEmail, email)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UnsubscribeToken,
		&i.UnsubscribedAt,
		&i.CreatedAt,
	)
	return i, err
}

const subscriberByID = `-- name: SubscriberByID :one
SELECT id, email, unsubscribe_token, unsubscribed_at, created_at FROM subscribers WHERE id = ? LIMIT 1
`

func (q *Queries) SubscriberByID(ctx context.Context, id int64) (Subscriber, error) {
	row := q.db.QueryRowContext(ctx, subscriberByID, id)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UnsubscribeToken,
		&i.UnsubscribedAt,
		&i.CreatedAt,
	)
	return i, err
}

const subscriberByUnsubscribeToken = `-- name: SubscriberByUnsubscribeToken :one
SELECT id, email, unsubscribe_token, unsubscribed_at, created_at FROM subscribers WHERE unsubscribe_token = ? LIMIT 1
`

func (q *Queries) SubscriberByUnsubscribeToken(ctx context.Context, unsubscribeToken string) (Subscriber, error) {
	row := q.db.QueryRowContext(ctx, subscriberByUnsubscribeToken, unsubscribeToken)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UnsubscribeToken,
		&i.UnsubscribedAt,
		&i.CreatedAt,
	)
	return i, err
}

const subscriberCreate = `-- name: SubscriberCreate :one
INSERT INTO subscribers (
    email, unsubscribe_token
) VALUES (
    ?, ?
)
RETURNING id, email, unsubscribe_token, unsubscribed_at, created_at
`

type SubscriberCreateParams struct {
	Email            string `json:"email"`
	UnsubscribeToken string `json:"unsubscribe_token"`
}

func (q *Queries) SubscriberCreate(ctx context.Context, arg SubscriberCreateParams) (Subscriber, error) {
	row := q.db.QueryRowContext(ctx, subscriberCreate, arg.Email, arg.UnsubscribeToken)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UnsubscribeToken,
		&i.UnsubscribedAt,
		&i.CreatedAt,
	)
	return i, err
}

const subscriberReactivate = `-- name: SubscriberReactivate :one
UPDATE subscribers
SET unsubscribed_at = NULL,
    unsubscribe_token = ?
WHERE email = ? AND unsubscribed_at IS NOT NULL
RETURNING id, email, unsubscribe_token, unsubscribed_at, created_at`

type SubscriberReactivateParams struct {
	UnsubscribeToken string `json:"unsubscribe_token"`
	Email            string `json:"email"`
}

func (q *Queries) SubscriberReactivate(ctx context.Context, arg SubscriberReactivateParams) (Subscriber, error) {
	row := q.db.QueryRowContext(ctx, subscriberReactivate, arg.UnsubscribeToken, arg.Email)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UnsubscribeToken,
		&i.UnsubscribedAt,
		&i.CreatedAt,
	)
	return i, err
}

const subscriberListActive = `-- name: SubscriberListActive :many
SELECT id, email, unsubscribe_token, unsubscribed_at, created_at FROM subscribers
WHERE unsubscribed_at IS NULL
ORDER BY id ASC
`

func (q *Queries) SubscriberListActive(ctx context.Context) ([]Subscriber, error) {
	rows, err := q.db.QueryContext(ctx, subscriberListActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscriber{}
	for rows.Next() {
		var i Subscriber
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.UnsubscribeToken,
			&i.UnsubscribedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subscriberCountActive = `-- name: SubscriberCountActive :one
SELECT COUNT(*) FROM subscribers WHERE unsubscribed_at IS NULL
`

func (q *Queries) SubscriberCountActive(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, subscriberCountActive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const subscriberUnsubscribe = `-- name: SubscriberUnsubscribe :exec
UPDATE subscribers
SET unsubscribed_at = CURRENT_TIMESTAMP
WHERE unsubscribe_token = ? AND unsubscribed_at IS NULL
`

func (q *Queries) SubscriberUnsubscribe(ctx context.Context, unsubscribeToken string) error {
	_, err := q.db.ExecContext(ctx, subscriberUnsubscribe, unsubscribeToken)
	return err
}
