// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issues.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const issueByID = `-- name: IssueByID :one
SELECT id, slug, sent_at, subject, summary, html_body, text_body, status FROM issues WHERE id = ? LIMIT 1
`

func (q *Queries) IssueByID(ctx context.Context, id int64) (Issue, error) {
	row := q.db.QueryRowContext(ctx, issueByID, id)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.SentAt,
		&i.Subject,
		&i.Summary,
		&i.HtmlBody,
		&i.TextBody,
		&i.Status,
	)
	return i, err
}

const issueBySlug = `-- name: IssueBySlug :one
SELECT id, slug, sent_at, subject, summary, html_body, text_body, status FROM issues WHERE slug = ? LIMIT 1
`

func (q *Queries) IssueBySlug(ctx context.Context, slug string) (Issue, error) {
	row := q.db.QueryRowContext(ctx, issueBySlug, slug)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.SentAt,
		&i.Subject,
		&i.Summary,
		&i.HtmlBody,
		&i.TextBody,
		&i.Status,
	)
	return i, err
}

const issueCount = `-- name: IssueCount :one
SELECT COUNT(*) FROM issues WHERE status = 'sent'
`

func (q *Queries) IssueCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, issueCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const issueCreate = `-- name: IssueCreate :one
INSERT INTO issues (
    slug, sent_at, subject, summary, html_body, text_body, status
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, slug, sent_at, subject, summary, html_body, text_body, status
`

type IssueCreateParams struct {
	Slug     string         `json:"slug"`
	SentAt   time.Time      `json:"sent_at"`
	Subject  string         `json:"subject"`
	Summary  sql.NullString `json:"summary"`
	HtmlBody string         `json:"html_body"`
	TextBody string         `json:"text_body"`
	Status   string         `json:"status"`
}

func (q *Queries) IssueCreate(ctx context.Context, arg IssueCreateParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, issueCreate,
		arg.Slug,
		arg.SentAt,
		arg.Subject,
		arg.Summary,
		arg.HtmlBody,
		arg.TextBody,
		arg.Status,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.SentAt,
		&i.Subject,
		&i.Summary,
		&i.HtmlBody,
		&i.TextBody,
		&i.Status,
	)
	return i, err
}

const issueList = `-- name: IssueList :many
SELECT id, slug, sent_at, subject, summary, html_body, text_body, status FROM issues
WHERE status = 'sent'
ORDER BY sent_at DESC
LIMIT ? OFFSET ?
`

type IssueListParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) IssueList(ctx context.Context, arg IssueListParams) ([]Issue, error) {
	rows, err := q.db.QueryContext(ctx, issueList, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.SentAt,
			&i.Subject,
			&i.Summary,
			&i.HtmlBody,
			&i.TextBody,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
