// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const confirmSubscriber = `-- name: ConfirmSubscriber :exec
UPDATE subscribers
SET confirmed_at = CURRENT_TIMESTAMP
WHERE confirm_token = ? AND confirmed_at IS NULL
`

func (q *Queries) ConfirmSubscriber(ctx context.Context, confirmToken string) error {
	_, err := q.db.ExecContext(ctx, confirmSubscriber, confirmToken)
	return err
}

const createNewsItem = `-- name: CreateNewsItem :one
INSERT INTO news_items (
    issue_id, source, title, url,
    author_name, author_username, author_avatar_url, author_profile_url,
    score, summary, position, raw_json
) VALUES (
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?
)
RETURNING id, issue_id, source, title, url, author_name, author_username, author_avatar_url, author_profile_url, score, summary, position, raw_json
`

type CreateNewsItemParams struct {
	IssueID          int64           `json:"issue_id"`
	Source           string          `json:"source"`
	Title            string          `json:"title"`
	Url              string          `json:"url"`
	AuthorName       sql.NullString  `json:"author_name"`
	AuthorUsername   sql.NullString  `json:"author_username"`
	AuthorAvatarUrl  sql.NullString  `json:"author_avatar_url"`
	AuthorProfileUrl sql.NullString  `json:"author_profile_url"`
	Score            sql.NullFloat64 `json:"score"`
	Summary          sql.NullString  `json:"summary"`
	Position         int64           `json:"position"`
	RawJson          sql.NullString  `json:"raw_json"`
}

func (q *Queries) CreateNewsItem(ctx context.Context, arg CreateNewsItemParams) (NewsItem, error) {
	row := q.db.QueryRowContext(ctx, createNewsItem,
		arg.IssueID,
		arg.Source,
		arg.Title,
		arg.Url,
		arg.AuthorName,
		arg.AuthorUsername,
		arg.AuthorAvatarUrl,
		arg.AuthorProfileUrl,
		arg.Score,
		arg.Summary,
		arg.Position,
		arg.RawJson,
	)
	var i NewsItem
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Source,
		&i.Title,
		&i.Url,
		&i.AuthorName,
		&i.AuthorUsername,
		&i.AuthorAvatarUrl,
		&i.AuthorProfileUrl,
		&i.Score,
		&i.Summary,
		&i.Position,
		&i.RawJson,
	)
	return i, err
}

const createSubscriber = `-- name: CreateSubscriber :one
INSERT INTO subscribers (
    email, confirm_token, unsubscribe_token
) VALUES (
    ?, ?, ?
)
RETURNING id, email, confirm_token, unsubscribe_token, confirmed_at, unsubscribed_at, created_at
`

type CreateSubscriberParams struct {
	Email            string `json:"email"`
	ConfirmToken     string `json:"confirm_token"`
	UnsubscribeToken string `json:"unsubscribe_token"`
}

func (q *Queries) CreateSubscriber(ctx context.Context, arg CreateSubscriberParams) (Subscriber, error) {
	row := q.db.QueryRowContext(ctx, createSubscriber, arg.Email, arg.ConfirmToken, arg.UnsubscribeToken)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ConfirmToken,
		&i.UnsubscribeToken,
		&i.ConfirmedAt,
		&i.UnsubscribedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNewsItemsByIssue = `-- name: DeleteNewsItemsByIssue :exec
DELETE FROM news_items WHERE issue_id = ?
`

func (q *Queries) DeleteNewsItemsByIssue(ctx context.Context, issueID int64) error {
	_, err := q.db.ExecContext(ctx, deleteNewsItemsByIssue, issueID)
	return err
}

const getNewsItem = `-- name: GetNewsItem :one
SELECT id, issue_id, source, title, url, author_name, author_username, author_avatar_url, author_profile_url, score, summary, position, raw_json FROM news_items WHERE id = ? LIMIT 1
`

func (q *Queries) GetNewsItem(ctx context.Context, id int64) (NewsItem, error) {
	row := q.db.QueryRowContext(ctx, getNewsItem, id)
	var i NewsItem
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Source,
		&i.Title,
		&i.Url,
		&i.AuthorName,
		&i.AuthorUsername,
		&i.AuthorAvatarUrl,
		&i.AuthorProfileUrl,
		&i.Score,
		&i.Summary,
		&i.Position,
		&i.RawJson,
	)
	return i, err
}

const getSubscriberByConfirmToken = `-- name: GetSubscriberByConfirmToken :one
SELECT id, email, confirm_token, unsubscribe_token, confirmed_at, unsubscribed_at, created_at FROM subscribers WHERE confirm_token = ? LIMIT 1
`

func (q *Queries) GetSubscriberByConfirmToken(ctx context.Context, confirmToken string) (Subscriber, error) {
	row := q.db.QueryRowContext(ctx, getSubscriberByConfirmToken, confirmToken)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ConfirmToken,
		&i.UnsubscribeToken,
		&i.ConfirmedAt,
		&i.UnsubscribedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSubscriberByEmail = `-- name: GetSubscriberByEmail :one
SELECT id, email, confirm_token, unsubscribe_token, confirmed_at, unsubscribed_at, created_at FROM subscribers WHERE email = ? LIMIT 1
`

func (q *Queries) GetSubscriberByEmail(ctx context.Context, email string) (Subscriber, error) {
	row := q.db.QueryRowContext(ctx, getSubscriberByEmail, email)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ConfirmToken,
		&i.UnsubscribeToken,
		&i.ConfirmedAt,
		&i.UnsubscribedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSubscriberByUnsubscribeToken = `-- name: GetSubscriberByUnsubscribeToken :one
SELECT id, email, confirm_token, unsubscribe_token, confirmed_at, unsubscribed_at, created_at FROM subscribers WHERE unsubscribe_token = ? LIMIT 1
`

func (q *Queries) GetSubscriberByUnsubscribeToken(ctx context.Context, unsubscribeToken string) (Subscriber, error) {
	row := q.db.QueryRowContext(ctx, getSubscriberByUnsubscribeToken, unsubscribeToken)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ConfirmToken,
		&i.UnsubscribeToken,
		&i.ConfirmedAt,
		&i.UnsubscribedAt,
		&i.CreatedAt,
	)
	return i, err
}

const issueByID = `-- name: IssueByID :one
SELECT id, slug, sent_at, subject, summary, html_body, text_body, status FROM issues WHERE id = ? LIMIT 1
`

func (q *Queries) IssueByID(ctx context.Context, id int64) (Issue, error) {
	row := q.db.QueryRowContext(ctx, issueByID, id)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.SentAt,
		&i.Subject,
		&i.Summary,
		&i.HtmlBody,
		&i.TextBody,
		&i.Status,
	)
	return i, err
}

const issueBySlug = `-- name: IssueBySlug :one
SELECT id, slug, sent_at, subject, summary, html_body, text_body, status FROM issues WHERE slug = ? LIMIT 1
`

func (q *Queries) IssueBySlug(ctx context.Context, slug string) (Issue, error) {
	row := q.db.QueryRowContext(ctx, issueBySlug, slug)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.SentAt,
		&i.Subject,
		&i.Summary,
		&i.HtmlBody,
		&i.TextBody,
		&i.Status,
	)
	return i, err
}

const issueCount = `-- name: IssueCount :one
SELECT COUNT(*) FROM issues WHERE status = 'sent'
`

func (q *Queries) IssueCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, issueCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const issueCreate = `-- name: IssueCreate :one
INSERT INTO issues (
    slug, sent_at, subject, summary, html_body, text_body, status
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, slug, sent_at, subject, summary, html_body, text_body, status
`

type IssueCreateParams struct {
	Slug     string         `json:"slug"`
	SentAt   time.Time      `json:"sent_at"`
	Subject  string         `json:"subject"`
	Summary  sql.NullString `json:"summary"`
	HtmlBody string         `json:"html_body"`
	TextBody string         `json:"text_body"`
	Status   string         `json:"status"`
}

func (q *Queries) IssueCreate(ctx context.Context, arg IssueCreateParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, issueCreate,
		arg.Slug,
		arg.SentAt,
		arg.Subject,
		arg.Summary,
		arg.HtmlBody,
		arg.TextBody,
		arg.Status,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.SentAt,
		&i.Subject,
		&i.Summary,
		&i.HtmlBody,
		&i.TextBody,
		&i.Status,
	)
	return i, err
}

const issueList = `-- name: IssueList :many
SELECT id, slug, sent_at, subject, summary, html_body, text_body, status FROM issues
WHERE status = 'sent'
ORDER BY sent_at DESC
LIMIT ? OFFSET ?
`

type IssueListParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) IssueList(ctx context.Context, arg IssueListParams) ([]Issue, error) {
	rows, err := q.db.QueryContext(ctx, issueList, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.SentAt,
			&i.Subject,
			&i.Summary,
			&i.HtmlBody,
			&i.TextBody,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSubscribers = `-- name: ListActiveSubscribers :many
SELECT id, email, confirm_token, unsubscribe_token, confirmed_at, unsubscribed_at, created_at FROM subscribers
WHERE confirmed_at IS NOT NULL AND unsubscribed_at IS NULL
ORDER BY id ASC
`

func (q *Queries) ListActiveSubscribers(ctx context.Context) ([]Subscriber, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSubscribers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscriber{}
	for rows.Next() {
		var i Subscriber
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.ConfirmToken,
			&i.UnsubscribeToken,
			&i.ConfirmedAt,
			&i.UnsubscribedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewsItemsByIssue = `-- name: ListNewsItemsByIssue :many
SELECT id, issue_id, source, title, url, author_name, author_username, author_avatar_url, author_profile_url, score, summary, position, raw_json FROM news_items
WHERE issue_id = ?
ORDER BY position ASC
`

func (q *Queries) ListNewsItemsByIssue(ctx context.Context, issueID int64) ([]NewsItem, error) {
	rows, err := q.db.QueryContext(ctx, listNewsItemsByIssue, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NewsItem{}
	for rows.Next() {
		var i NewsItem
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.Source,
			&i.Title,
			&i.Url,
			&i.AuthorName,
			&i.AuthorUsername,
			&i.AuthorAvatarUrl,
			&i.AuthorProfileUrl,
			&i.Score,
			&i.Summary,
			&i.Position,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unsubscribeByToken = `-- name: UnsubscribeByToken :exec
UPDATE subscribers
SET unsubscribed_at = CURRENT_TIMESTAMP
WHERE unsubscribe_token = ? AND unsubscribed_at IS NULL
`

func (q *Queries) UnsubscribeByToken(ctx context.Context, unsubscribeToken string) error {
	_, err := q.db.ExecContext(ctx, unsubscribeByToken, unsubscribeToken)
	return err
}
