// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ainsleyclark/godaily/pkg/services/subscriber (interfaces: Subscriber)
//
// Generated by this command:
//
//	mockgen -package=mocksubscriber -destination=../../mocks/subscriber/Subscriber.go . Subscriber
//

// Package mocksubscriber is a generated GoMock package.
package mocksubscriber

import (
	context "context"
	reflect "reflect"

	news "github.com/ainsleyclark/godaily/pkg/domain/news"
	gomock "go.uber.org/mock/gomock"
)

// MockSubscriber is a mock of Subscriber interface.
type MockSubscriber struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriberMockRecorder
	isgomock struct{}
}

// MockSubscriberMockRecorder is the mock recorder for MockSubscriber.
type MockSubscriberMockRecorder struct {
	mock *MockSubscriber
}

// NewMockSubscriber creates a new mock instance.
func NewMockSubscriber(ctrl *gomock.Controller) *MockSubscriber {
	mock := &MockSubscriber{ctrl: ctrl}
	mock.recorder = &MockSubscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriber) EXPECT() *MockSubscriberMockRecorder {
	return m.recorder
}

// Confirm mocks base method.
func (m *MockSubscriber) Confirm(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Confirm", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Confirm indicates an expected call of Confirm.
func (mr *MockSubscriberMockRecorder) Confirm(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Confirm", reflect.TypeOf((*MockSubscriber)(nil).Confirm), ctx, token)
}

// MarkBounced mocks base method.
func (m *MockSubscriber) MarkBounced(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkBounced", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkBounced indicates an expected call of MarkBounced.
func (mr *MockSubscriberMockRecorder) MarkBounced(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkBounced", reflect.TypeOf((*MockSubscriber)(nil).MarkBounced), ctx, email)
}

// MarkComplained mocks base method.
func (m *MockSubscriber) MarkComplained(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkComplained", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkComplained indicates an expected call of MarkComplained.
func (mr *MockSubscriberMockRecorder) MarkComplained(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkComplained", reflect.TypeOf((*MockSubscriber)(nil).MarkComplained), ctx, email)
}

// MarkUnsubscribed mocks base method.
func (m *MockSubscriber) MarkUnsubscribed(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkUnsubscribed", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkUnsubscribed indicates an expected call of MarkUnsubscribed.
func (mr *MockSubscriberMockRecorder) MarkUnsubscribed(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkUnsubscribed", reflect.TypeOf((*MockSubscriber)(nil).MarkUnsubscribed), ctx, email)
}

// Subscribe mocks base method.
func (m *MockSubscriber) Subscribe(ctx context.Context, email string) (news.Subscriber, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, email)
	ret0, _ := ret[0].(news.Subscriber)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockSubscriberMockRecorder) Subscribe(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockSubscriber)(nil).Subscribe), ctx, email)
}

// Unsubscribe mocks base method.
func (m *MockSubscriber) Unsubscribe(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unsubscribe", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockSubscriberMockRecorder) Unsubscribe(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockSubscriber)(nil).Unsubscribe), ctx, token)
}
