// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type logoEntry struct {
	src string
	alt string
}

var logoItems = []logoEntry{
	{"/assets/images/logos/go.svg", "Go"},
	{"/assets/images/logos/github.svg", "GitHub"},
	{"/assets/images/logos/jetbrains.svg", "JetBrains"},
	{"/assets/images/logos/reddit.svg", "Reddit"},
	{"/assets/images/logos/devto.svg", "DEV.to"},
	{"/assets/images/logos/medium.svg", "Medium"},
	{"/assets/images/logos/goland.svg", "GoLand"},
	{"/assets/images/logos/youtube.svg", "YouTube"},
	{"/assets/images/logos/ardanlabs_podcast.svg", "Ardan Labs Podcast"},
	{"/assets/images/logos/mastodon.svg", "Mastodon"},
	{"/assets/images/logos/linkedin.png", "LinkedIn"},
	{"/assets/images/logos/bluesky.svg", "Bluesky"},
	{"/assets/images/logos/golang-bridge.png", "Golang Bridge"},
	{"/assets/images/logos/hacker-news.svg", "Hacker News"},
	{"/assets/images/logos/meetup.svg", "Meetup"},
	{"/assets/images/logos/fcc.svg", "freeCodeCamp"},
	{"/assets/images/logos/remoteok.png", "Remote OK"},
	{"/assets/images/logos/remotive.svg", "Remotive"},
	{"/assets/images/logos/we_work_remotely.svg", "We Work Remotely"},
	{"/assets/images/logos/golang_projects.png", "Golangprojects"},
}

func Logos() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"logo-ticker\" aria-hidden=\"true\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, l := range logoItems {
				templ_7745c5c3_Err = Picture(l.src, l.alt, "logo-ticker__img", templ.Attributes{"height": "34", "width": "auto"}).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Container(false).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
