// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ainsleyclark/godaily/pkg/domain/email (interfaces: EventRepository)
//
// Generated by this command:
//
//	mockgen -package=mockemail -destination=../../mocks/domain/email/EventRepository.go . EventRepository
//

// Package mockemail is a generated GoMock package.
package mockemail

import (
	context "context"
	reflect "reflect"

	email "github.com/ainsleyclark/godaily/pkg/domain/email"
	gomock "go.uber.org/mock/gomock"
)

// MockEventRepository is a mock of EventRepository interface.
type MockEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEventRepositoryMockRecorder
	isgomock struct{}
}

// MockEventRepositoryMockRecorder is the mock recorder for MockEventRepository.
type MockEventRepositoryMockRecorder struct {
	mock *MockEventRepository
}

// NewMockEventRepository creates a new mock instance.
func NewMockEventRepository(ctrl *gomock.Controller) *MockEventRepository {
	mock := &MockEventRepository{ctrl: ctrl}
	mock.recorder = &MockEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventRepository) EXPECT() *MockEventRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEventRepository) Create(ctx context.Context, e email.Event) (email.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, e)
	ret0, _ := ret[0].(email.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockEventRepositoryMockRecorder) Create(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEventRepository)(nil).Create), ctx, e)
}

// ExistsByEventID mocks base method.
func (m *MockEventRepository) ExistsByEventID(ctx context.Context, eventID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByEventID", ctx, eventID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByEventID indicates an expected call of ExistsByEventID.
func (mr *MockEventRepositoryMockRecorder) ExistsByEventID(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByEventID", reflect.TypeOf((*MockEventRepository)(nil).ExistsByEventID), ctx, eventID)
}

// IssueStats mocks base method.
func (m *MockEventRepository) IssueStats(ctx context.Context, issueID int64) (email.IssueStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueStats", ctx, issueID)
	ret0, _ := ret[0].(email.IssueStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueStats indicates an expected call of IssueStats.
func (mr *MockEventRepositoryMockRecorder) IssueStats(ctx, issueID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueStats", reflect.TypeOf((*MockEventRepository)(nil).IssueStats), ctx, issueID)
}

// TopLinks mocks base method.
func (m *MockEventRepository) TopLinks(ctx context.Context, issueID, limit int64) ([]email.LinkClicks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TopLinks", ctx, issueID, limit)
	ret0, _ := ret[0].([]email.LinkClicks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TopLinks indicates an expected call of TopLinks.
func (mr *MockEventRepositoryMockRecorder) TopLinks(ctx, issueID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TopLinks", reflect.TypeOf((*MockEventRepository)(nil).TopLinks), ctx, issueID, limit)
}
