// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ainsleyclark/godaily/pkg/news (interfaces: SubscriberRepository)
//
// Generated by this command:
//
//	mockgen -package=mocknews -destination=../mocks/news/SubscriberRepository.go . SubscriberRepository
//

// Package mocknews is a generated GoMock package.
package mocknews

import (
	context "context"
	reflect "reflect"

	news "github.com/ainsleyclark/godaily/pkg/news"
	gomock "go.uber.org/mock/gomock"
)

// MockSubscriberRepository is a mock of SubscriberRepository interface.
type MockSubscriberRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriberRepositoryMockRecorder
	isgomock struct{}
}

// MockSubscriberRepositoryMockRecorder is the mock recorder for MockSubscriberRepository.
type MockSubscriberRepositoryMockRecorder struct {
	mock *MockSubscriberRepository
}

// NewMockSubscriberRepository creates a new mock instance.
func NewMockSubscriberRepository(ctrl *gomock.Controller) *MockSubscriberRepository {
	mock := &MockSubscriberRepository{ctrl: ctrl}
	mock.recorder = &MockSubscriberRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriberRepository) EXPECT() *MockSubscriberRepositoryMockRecorder {
	return m.recorder
}

// CountActive mocks base method.
func (m *MockSubscriberRepository) CountActive(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActive", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActive indicates an expected call of CountActive.
func (mr *MockSubscriberRepositoryMockRecorder) CountActive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActive", reflect.TypeOf((*MockSubscriberRepository)(nil).CountActive), ctx)
}

// Confirm mocks base method.
func (m *MockSubscriberRepository) Confirm(ctx context.Context, token string) (news.Subscriber, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Confirm", ctx, token)
	ret0, _ := ret[0].(news.Subscriber)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Confirm indicates an expected call of Confirm.
func (mr *MockSubscriberRepositoryMockRecorder) Confirm(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Confirm", reflect.TypeOf((*MockSubscriberRepository)(nil).Confirm), ctx, token)
}

// Create mocks base method.
func (m *MockSubscriberRepository) Create(ctx context.Context, email string) (news.Subscriber, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, email)
	ret0, _ := ret[0].(news.Subscriber)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSubscriberRepositoryMockRecorder) Create(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSubscriberRepository)(nil).Create), ctx, email)
}

// Find mocks base method.
func (m *MockSubscriberRepository) Find(ctx context.Context, id int64) (news.Subscriber, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(news.Subscriber)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockSubscriberRepositoryMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockSubscriberRepository)(nil).Find), ctx, id)
}

// FindByEmail mocks base method.
func (m *MockSubscriberRepository) FindByEmail(ctx context.Context, email string) (news.Subscriber, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", ctx, email)
	ret0, _ := ret[0].(news.Subscriber)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockSubscriberRepositoryMockRecorder) FindByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockSubscriberRepository)(nil).FindByEmail), ctx, email)
}

// FindByUnsubscribeToken mocks base method.
func (m *MockSubscriberRepository) FindByUnsubscribeToken(ctx context.Context, token string) (news.Subscriber, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUnsubscribeToken", ctx, token)
	ret0, _ := ret[0].(news.Subscriber)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUnsubscribeToken indicates an expected call of FindByUnsubscribeToken.
func (mr *MockSubscriberRepositoryMockRecorder) FindByUnsubscribeToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUnsubscribeToken", reflect.TypeOf((*MockSubscriberRepository)(nil).FindByUnsubscribeToken), ctx, token)
}

// ListActive mocks base method.
func (m *MockSubscriberRepository) ListActive(ctx context.Context) ([]news.Subscriber, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActive", ctx)
	ret0, _ := ret[0].([]news.Subscriber)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActive indicates an expected call of ListActive.
func (mr *MockSubscriberRepositoryMockRecorder) ListActive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActive", reflect.TypeOf((*MockSubscriberRepository)(nil).ListActive), ctx)
}

// Reactivate mocks base method.
func (m *MockSubscriberRepository) Reactivate(ctx context.Context, email string) (news.Subscriber, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reactivate", ctx, email)
	ret0, _ := ret[0].(news.Subscriber)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reactivate indicates an expected call of Reactivate.
func (mr *MockSubscriberRepositoryMockRecorder) Reactivate(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reactivate", reflect.TypeOf((*MockSubscriberRepository)(nil).Reactivate), ctx, email)
}

// Unsubscribe mocks base method.
func (m *MockSubscriberRepository) Unsubscribe(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unsubscribe", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockSubscriberRepositoryMockRecorder) Unsubscribe(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockSubscriberRepository)(nil).Unsubscribe), ctx, token)
}
