// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package graphics

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "fmt"

func GopherLogo(size int) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<svg width=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", size))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/views/graphics/gopher.templ`, Line: 7, Col: 33}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" height=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", size))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/views/graphics/gopher.templ`, Line: 8, Col: 34}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" viewBox=\"0 0 60 60\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"16\" cy=\"19\" r=\"9\" fill=\"#8DCFE8\"></circle> <ellipse cx=\"16\" cy=\"21\" rx=\"5.5\" ry=\"5\" fill=\"#C48A5E\"></ellipse> <circle cx=\"44\" cy=\"19\" r=\"9\" fill=\"#8DCFE8\"></circle> <ellipse cx=\"44\" cy=\"21\" rx=\"5.5\" ry=\"5\" fill=\"#C48A5E\"></ellipse> <ellipse cx=\"30\" cy=\"36\" rx=\"23\" ry=\"21\" fill=\"#8DCFE8\"></ellipse> <ellipse cx=\"30\" cy=\"42\" rx=\"13\" ry=\"9\" fill=\"#CCE8F5\"></ellipse> <circle cx=\"21\" cy=\"31\" r=\"8\" fill=\"white\"></circle> <circle cx=\"39\" cy=\"31\" r=\"8\" fill=\"white\"></circle> <circle cx=\"22.5\" cy=\"31.5\" r=\"5\" fill=\"#0d2236\"></circle> <circle cx=\"40.5\" cy=\"31.5\" r=\"5\" fill=\"#0d2236\"></circle> <circle cx=\"24\" cy=\"29.5\" r=\"1.8\" fill=\"white\"></circle> <circle cx=\"42\" cy=\"29.5\" r=\"1.8\" fill=\"white\"></circle> <ellipse cx=\"30\" cy=\"42\" rx=\"8\" ry=\"5.5\" fill=\"#D4A07A\"></ellipse> <ellipse cx=\"30\" cy=\"39\" rx=\"3\" ry=\"2\" fill=\"#1a1a2e\"></ellipse> <rect x=\"26.5\" y=\"44\" width=\"3.5\" height=\"4.5\" rx=\"1\" fill=\"white\"></rect> <rect x=\"30.5\" y=\"44\" width=\"3.5\" height=\"4.5\" rx=\"1\" fill=\"white\"></rect></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
