// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: news_items.sql

package store

import (
	"context"
	"database/sql"
)

const createNewsItem = `-- name: CreateNewsItem :one
INSERT INTO news_items (
    issue_id, source, title, url,
    author_name, author_username, author_avatar_url, author_profile_url,
    score, summary, position, raw_json
) VALUES (
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?
)
RETURNING id, issue_id, source, title, url, author_name, author_username, author_avatar_url, author_profile_url, score, summary, position, raw_json
`

type CreateNewsItemParams struct {
	IssueID          int64           `json:"issue_id"`
	Source           string          `json:"source"`
	Title            string          `json:"title"`
	Url              string          `json:"url"`
	AuthorName       sql.NullString  `json:"author_name"`
	AuthorUsername   sql.NullString  `json:"author_username"`
	AuthorAvatarUrl  sql.NullString  `json:"author_avatar_url"`
	AuthorProfileUrl sql.NullString  `json:"author_profile_url"`
	Score            sql.NullFloat64 `json:"score"`
	Summary          sql.NullString  `json:"summary"`
	Position         int64           `json:"position"`
	RawJson          sql.NullString  `json:"raw_json"`
}

func (q *Queries) CreateNewsItem(ctx context.Context, arg CreateNewsItemParams) (NewsItem, error) {
	row := q.db.QueryRowContext(ctx, createNewsItem,
		arg.IssueID,
		arg.Source,
		arg.Title,
		arg.Url,
		arg.AuthorName,
		arg.AuthorUsername,
		arg.AuthorAvatarUrl,
		arg.AuthorProfileUrl,
		arg.Score,
		arg.Summary,
		arg.Position,
		arg.RawJson,
	)
	var i NewsItem
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Source,
		&i.Title,
		&i.Url,
		&i.AuthorName,
		&i.AuthorUsername,
		&i.AuthorAvatarUrl,
		&i.AuthorProfileUrl,
		&i.Score,
		&i.Summary,
		&i.Position,
		&i.RawJson,
	)
	return i, err
}

const deleteNewsItemsByIssue = `-- name: DeleteNewsItemsByIssue :exec
DELETE FROM news_items WHERE issue_id = ?
`

func (q *Queries) DeleteNewsItemsByIssue(ctx context.Context, issueID int64) error {
	_, err := q.db.ExecContext(ctx, deleteNewsItemsByIssue, issueID)
	return err
}

const getNewsItem = `-- name: GetNewsItem :one
SELECT id, issue_id, source, title, url, author_name, author_username, author_avatar_url, author_profile_url, score, summary, position, raw_json FROM news_items WHERE id = ? LIMIT 1
`

func (q *Queries) GetNewsItem(ctx context.Context, id int64) (NewsItem, error) {
	row := q.db.QueryRowContext(ctx, getNewsItem, id)
	var i NewsItem
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Source,
		&i.Title,
		&i.Url,
		&i.AuthorName,
		&i.AuthorUsername,
		&i.AuthorAvatarUrl,
		&i.AuthorProfileUrl,
		&i.Score,
		&i.Summary,
		&i.Position,
		&i.RawJson,
	)
	return i, err
}

const listNewsItemsByIssue = `-- name: ListNewsItemsByIssue :many
SELECT id, issue_id, source, title, url, author_name, author_username, author_avatar_url, author_profile_url, score, summary, position, raw_json FROM news_items
WHERE issue_id = ?
ORDER BY position ASC
`

func (q *Queries) ListNewsItemsByIssue(ctx context.Context, issueID int64) ([]NewsItem, error) {
	rows, err := q.db.QueryContext(ctx, listNewsItemsByIssue, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NewsItem{}
	for rows.Next() {
		var i NewsItem
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.Source,
			&i.Title,
			&i.Url,
			&i.AuthorName,
			&i.AuthorUsername,
			&i.AuthorAvatarUrl,
			&i.AuthorProfileUrl,
			&i.Score,
			&i.Summary,
			&i.Position,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
