// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ainsleyclark/godaily/pkg/domain/engagement (interfaces: EmailEventRepository)
//
// Generated by this command:
//
//	mockgen -package=mockengagement -destination=../../mocks/engagement/EmailEventRepository.go . EmailEventRepository
//

// Package mockengagement is a generated GoMock package.
package mockengagement

import (
	context "context"
	reflect "reflect"

	engagement "github.com/ainsleyclark/godaily/pkg/domain/engagement"
	gomock "go.uber.org/mock/gomock"
)

// MockEmailEventRepository is a mock of EmailEventRepository interface.
type MockEmailEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmailEventRepositoryMockRecorder
	isgomock struct{}
}

// MockEmailEventRepositoryMockRecorder is the mock recorder for MockEmailEventRepository.
type MockEmailEventRepositoryMockRecorder struct {
	mock *MockEmailEventRepository
}

// NewMockEmailEventRepository creates a new mock instance.
func NewMockEmailEventRepository(ctrl *gomock.Controller) *MockEmailEventRepository {
	mock := &MockEmailEventRepository{ctrl: ctrl}
	mock.recorder = &MockEmailEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailEventRepository) EXPECT() *MockEmailEventRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEmailEventRepository) Create(ctx context.Context, e engagement.EmailEvent) (engagement.EmailEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, e)
	ret0, _ := ret[0].(engagement.EmailEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockEmailEventRepositoryMockRecorder) Create(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEmailEventRepository)(nil).Create), ctx, e)
}

// ExistsByEventID mocks base method.
func (m *MockEmailEventRepository) ExistsByEventID(ctx context.Context, eventID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByEventID", ctx, eventID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByEventID indicates an expected call of ExistsByEventID.
func (mr *MockEmailEventRepositoryMockRecorder) ExistsByEventID(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByEventID", reflect.TypeOf((*MockEmailEventRepository)(nil).ExistsByEventID), ctx, eventID)
}

// IssueStats mocks base method.
func (m *MockEmailEventRepository) IssueStats(ctx context.Context, issueID int64) (engagement.IssueStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueStats", ctx, issueID)
	ret0, _ := ret[0].(engagement.IssueStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueStats indicates an expected call of IssueStats.
func (mr *MockEmailEventRepositoryMockRecorder) IssueStats(ctx, issueID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueStats", reflect.TypeOf((*MockEmailEventRepository)(nil).IssueStats), ctx, issueID)
}

// TopLinks mocks base method.
func (m *MockEmailEventRepository) TopLinks(ctx context.Context, issueID, limit int64) ([]engagement.LinkClicks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TopLinks", ctx, issueID, limit)
	ret0, _ := ret[0].([]engagement.LinkClicks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TopLinks indicates an expected call of TopLinks.
func (mr *MockEmailEventRepositoryMockRecorder) TopLinks(ctx, issueID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TopLinks", reflect.TypeOf((*MockEmailEventRepository)(nil).TopLinks), ctx, issueID, limit)
}
