// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ainsleyclark/godaily/pkg/domain/engagement (interfaces: EventService)
//
// Generated by this command:
//
//	mockgen -package=mockengagement -destination=../../mocks/engagement/EventService.go . EventService
//

// Package mockengagement is a generated GoMock package.
package mockengagement

import (
	context "context"
	reflect "reflect"

	engagement "github.com/ainsleyclark/godaily/pkg/domain/engagement"
	gomock "go.uber.org/mock/gomock"
)

// MockEventService is a mock of EventService interface.
type MockEventService struct {
	ctrl     *gomock.Controller
	recorder *MockEventServiceMockRecorder
	isgomock struct{}
}

// MockEventServiceMockRecorder is the mock recorder for MockEventService.
type MockEventServiceMockRecorder struct {
	mock *MockEventService
}

// NewMockEventService creates a new mock instance.
func NewMockEventService(ctrl *gomock.Controller) *MockEventService {
	mock := &MockEventService{ctrl: ctrl}
	mock.recorder = &MockEventServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventService) EXPECT() *MockEventServiceMockRecorder {
	return m.recorder
}

// Process mocks base method.
func (m *MockEventService) Process(ctx context.Context, e engagement.EmailEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Process indicates an expected call of Process.
func (mr *MockEventServiceMockRecorder) Process(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockEventService)(nil).Process), ctx, e)
}
