// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ainsleyclark/godaily/pkg/domain/engagement (interfaces: MetricsRepository)
//
// Generated by this command:
//
//	mockgen -package=mockengagement -destination=../../mocks/engagement/MetricsRepository.go . MetricsRepository
//

// Package mockengagement is a generated GoMock package.
package mockengagement

import (
	context "context"
	reflect "reflect"

	engagement "github.com/ainsleyclark/godaily/pkg/domain/engagement"
	gomock "go.uber.org/mock/gomock"
)

// MockMetricsRepository is a mock of MetricsRepository interface.
type MockMetricsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsRepositoryMockRecorder
	isgomock struct{}
}

// MockMetricsRepositoryMockRecorder is the mock recorder for MockMetricsRepository.
type MockMetricsRepositoryMockRecorder struct {
	mock *MockMetricsRepository
}

// NewMockMetricsRepository creates a new mock instance.
func NewMockMetricsRepository(ctrl *gomock.Controller) *MockMetricsRepository {
	mock := &MockMetricsRepository{ctrl: ctrl}
	mock.recorder = &MockMetricsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsRepository) EXPECT() *MockMetricsRepositoryMockRecorder {
	return m.recorder
}

// IssueList mocks base method.
func (m *MockMetricsRepository) IssueList(ctx context.Context, f engagement.MetricsFilter, sort string) ([]engagement.IssueEngagement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueList", ctx, f, sort)
	ret0, _ := ret[0].([]engagement.IssueEngagement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueList indicates an expected call of IssueList.
func (mr *MockMetricsRepositoryMockRecorder) IssueList(ctx, f, sort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueList", reflect.TypeOf((*MockMetricsRepository)(nil).IssueList), ctx, f, sort)
}

// ItemList mocks base method.
func (m *MockMetricsRepository) ItemList(ctx context.Context, f engagement.MetricsFilter) ([]engagement.ItemMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ItemList", ctx, f)
	ret0, _ := ret[0].([]engagement.ItemMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ItemList indicates an expected call of ItemList.
func (mr *MockMetricsRepositoryMockRecorder) ItemList(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ItemList", reflect.TypeOf((*MockMetricsRepository)(nil).ItemList), ctx, f)
}

// SourceList mocks base method.
func (m *MockMetricsRepository) SourceList(ctx context.Context, f engagement.MetricsFilter) ([]engagement.SourceMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SourceList", ctx, f)
	ret0, _ := ret[0].([]engagement.SourceMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SourceList indicates an expected call of SourceList.
func (mr *MockMetricsRepositoryMockRecorder) SourceList(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SourceList", reflect.TypeOf((*MockMetricsRepository)(nil).SourceList), ctx, f)
}

// SubscriberGrowth mocks base method.
func (m *MockMetricsRepository) SubscriberGrowth(ctx context.Context, f engagement.MetricsFilter, bucket string) (engagement.SubscriberData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscriberGrowth", ctx, f, bucket)
	ret0, _ := ret[0].(engagement.SubscriberData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscriberGrowth indicates an expected call of SubscriberGrowth.
func (mr *MockMetricsRepositoryMockRecorder) SubscriberGrowth(ctx, f, bucket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscriberGrowth", reflect.TypeOf((*MockMetricsRepository)(nil).SubscriberGrowth), ctx, f, bucket)
}

// Summary mocks base method.
func (m *MockMetricsRepository) Summary(ctx context.Context, f engagement.MetricsFilter) (engagement.SummaryStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Summary", ctx, f)
	ret0, _ := ret[0].(engagement.SummaryStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Summary indicates an expected call of Summary.
func (mr *MockMetricsRepositoryMockRecorder) Summary(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Summary", reflect.TypeOf((*MockMetricsRepository)(nil).Summary), ctx, f)
}

// TagList mocks base method.
func (m *MockMetricsRepository) TagList(ctx context.Context, f engagement.MetricsFilter) ([]engagement.TagMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TagList", ctx, f)
	ret0, _ := ret[0].([]engagement.TagMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TagList indicates an expected call of TagList.
func (mr *MockMetricsRepositoryMockRecorder) TagList(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagList", reflect.TypeOf((*MockMetricsRepository)(nil).TagList), ctx, f)
}

// Trend mocks base method.
func (m *MockMetricsRepository) Trend(ctx context.Context, f engagement.MetricsFilter, metric, bucket string) (engagement.TrendData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trend", ctx, f, metric, bucket)
	ret0, _ := ret[0].(engagement.TrendData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Trend indicates an expected call of Trend.
func (mr *MockMetricsRepositoryMockRecorder) Trend(ctx, f, metric, bucket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trend", reflect.TypeOf((*MockMetricsRepository)(nil).Trend), ctx, f, metric, bucket)
}
