// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ainsleyclark/godaily/pkg/domain/engagement (interfaces: MetricsReporter)
//
// Generated by this command:
//
//	mockgen -package=mockengagement -destination=../../mocks/engagement/MetricsReporter.go . MetricsReporter
//

// Package mockengagement is a generated GoMock package.
package mockengagement

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMetricsReporter is a mock of MetricsReporter interface.
type MockMetricsReporter struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsReporterMockRecorder
	isgomock struct{}
}

// MockMetricsReporterMockRecorder is the mock recorder for MockMetricsReporter.
type MockMetricsReporterMockRecorder struct {
	mock *MockMetricsReporter
}

// NewMockMetricsReporter creates a new mock instance.
func NewMockMetricsReporter(ctrl *gomock.Controller) *MockMetricsReporter {
	mock := &MockMetricsReporter{ctrl: ctrl}
	mock.recorder = &MockMetricsReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsReporter) EXPECT() *MockMetricsReporterMockRecorder {
	return m.recorder
}

// Roundup mocks base method.
func (m *MockMetricsReporter) Roundup(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Roundup", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Roundup indicates an expected call of Roundup.
func (mr *MockMetricsReporterMockRecorder) Roundup(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Roundup", reflect.TypeOf((*MockMetricsReporter)(nil).Roundup), ctx)
}
