// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ainsleyclark/godaily/pkg/domain/engagement (interfaces: SocialMetricRepository)
//
// Generated by this command:
//
//	mockgen -package=mockengagement -destination=../../mocks/engagement/SocialMetricRepository.go . SocialMetricRepository
//

// Package mockengagement is a generated GoMock package.
package mockengagement

import (
	context "context"
	reflect "reflect"

	engagement "github.com/ainsleyclark/godaily/pkg/domain/engagement"
	gomock "go.uber.org/mock/gomock"
)

// MockSocialMetricRepository is a mock of SocialMetricRepository interface.
type MockSocialMetricRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSocialMetricRepositoryMockRecorder
	isgomock struct{}
}

// MockSocialMetricRepositoryMockRecorder is the mock recorder for MockSocialMetricRepository.
type MockSocialMetricRepositoryMockRecorder struct {
	mock *MockSocialMetricRepository
}

// NewMockSocialMetricRepository creates a new mock instance.
func NewMockSocialMetricRepository(ctrl *gomock.Controller) *MockSocialMetricRepository {
	mock := &MockSocialMetricRepository{ctrl: ctrl}
	mock.recorder = &MockSocialMetricRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSocialMetricRepository) EXPECT() *MockSocialMetricRepositoryMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockSocialMetricRepository) List(ctx context.Context, f engagement.MetricsFilter) ([]engagement.SocialPostEngagement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, f)
	ret0, _ := ret[0].([]engagement.SocialPostEngagement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSocialMetricRepositoryMockRecorder) List(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSocialMetricRepository)(nil).List), ctx, f)
}

// ListBySocialPostID mocks base method.
func (m *MockSocialMetricRepository) ListBySocialPostID(ctx context.Context, socialPostID int64) ([]engagement.SocialMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBySocialPostID", ctx, socialPostID)
	ret0, _ := ret[0].([]engagement.SocialMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBySocialPostID indicates an expected call of ListBySocialPostID.
func (mr *MockSocialMetricRepositoryMockRecorder) ListBySocialPostID(ctx, socialPostID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBySocialPostID", reflect.TypeOf((*MockSocialMetricRepository)(nil).ListBySocialPostID), ctx, socialPostID)
}

// Upsert mocks base method.
func (m_2 *MockSocialMetricRepository) Upsert(ctx context.Context, m engagement.SocialMetric) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Upsert", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockSocialMetricRepositoryMockRecorder) Upsert(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockSocialMetricRepository)(nil).Upsert), ctx, m)
}
